routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\User\DashboardController as UserDashboardController;
use App\Http\Controllers\User\MyBookingListController;
use App\Http\Controllers\User\RoomListController;

use App\Http\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\RoomController;
use App\Http\Controllers\Admin\BookingListController;

use App\Http\Controllers\ChangePassController;

// use Illuminate\Support\Facades\Mail;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false, 'reset' => false, 'verify' => false]);

Route::prefix('/')
    ->get('/', [UserDashboardController::class, 'index'])
    /* 
    |--------------------------------------------------------------------------
    | Which Home Middleware
    |--------------------------------------------------------------------------
    | Which home middleware to support one login page for multiple user
    | because static var HOME which is the destnation after user login is '/'. 
    | It is checking user's role, user or admin. if someone login with 
    | user role then redirect to '/' or user's dashboard and that's it. but if  
    | the role is admin then first go to '/' which is user's dashboard and then 
    | redirect to '/admin' or admin's dashboard.
    */
    ->middleware(['auth', 'which.home'])
    ->name('user.dashboard');

Route::prefix('/')
    ->middleware(['auth', 'is.user'])
    ->group(function(){
        Route::get('/dashboard-booking-list', [UserDashboardController::class, 'dashboard_booking_list'])
        ->name('dashboard.booking-list');
        Route::get('/room/json', [RoomListController::class, 'json'])
        ->name('room-list.json');
        Route::get('/room', [RoomListController::class, 'index'])
        ->name('room-list.index');

        Route::get('/my-booking-list/json', [MyBookingListController::class, 'json'])
        ->name('my-booking-list.json');
        Route::get('/my-booking-list', [MyBookingListController::class, 'index'])
        ->name('my-booking-list.index');
        Route::get('/my-booking-list/create', [MyBookingListController::class, 'create'])
        ->name('my-booking-list.create');
        Route::post('/my-booking-list/store', [MyBookingListController::class, 'store'])
        ->name('my-booking-list.store');
        Route::put('/my-booking-list/{id}/cancel', [MyBookingListController::class, 'cancel'])
        ->name('my-booking-list.cancel');

        // Route::get('/mail', function () {
        //     Mail::to('fajarwindhuzulfikar@gmail.com')
        //         ->send(new \App\Mail\BookingMail('Booking Ruangan 3', 'Admin'));
        //     return 'Terkirim';
        // });
    });

Route::prefix('admin')
    ->middleware(['auth', 'is.admin'])
    ->group(function(){
        Route::get('/', [AdminDashboardController::class, 'index'])
        ->name('admin.dashboard');

        Route::get('/user/json', [UserController::class, 'json'])
        ->name('user.json');

        Route::get('/user/{id}/change-pass', [UserController::class, 'change_pass'])
        ->name('user.change-pass');

        Route::put('/user/{id}/update-pass', [UserController::class, 'update_pass'])
        ->name('user.update-pass');

        Route::get('/room/json', [RoomController::class, 'json'])
        ->name('room.json');

        Route::get('/booking-list/json', [BookingListController::class, 'json'])
        ->name('booking-list.json');

        Route::get('/booking-list', [BookingListController::class, 'index'])
        ->name('booking-list.index');

        Route::put('/booking-list/{id}/update/{value}', [BookingListController::class, 'update'])
        ->name('booking-list.update');

        Route::resources([
            'user'          => UserController::class,
            'room'          => RoomController::class,
        ]);
    });

/* 
| So basically we have 2 users here, USER and ADMIN. USER prefix is '/'
| and ADMIN prefix is 'admin'. Here we have change password feature that 
| can be used by either USER nor ADMIN.
*/

$users = [
    '/', 'admin',
];

foreach ($users as $user) {
    Route::prefix($user)
    ->middleware(['auth'])
    ->group(function () use ($user) {
        if($user == '/') $user = 'user';
        Route::get('/change-pass', [ChangePassController::class, 'index'])
        ->name($user.'.change-pass.index');
        Route::put('/change-pass/update', [ChangePassController::class, 'update'])
        ->name($user.'.change-pass.update');
    });
}

resources/views/includes/main/footer.blade.php
<footer class="main-footer">
  <div class="footer-left">
    &copy; TREEHOTEL 2021 - Present by <a href="https://fajarwz.netlify.app" target="_blank">Bismillah</a> <div class="bullet"></div> Powered by BarengSaya &copy; 2022 by <a href="https://nauval.in/" target="_blank">NoerV</a>
  </div>
  <div class="footer-right">
    1.0
  </div>
</footer>

resources/views/includes/main/navbar.blade.php
<div class="navbar-bg"></div>
<nav class="navbar navbar-expand-lg main-navbar">
  <form class="form-inline mr-auto">
    <ul class="navbar-nav mr-3">
      <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
    </ul>
  </form>
  <ul class="navbar-nav navbar-right">
    <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
      <img alt="image" src="{{ asset('theme/img/avatar/avatar-1.png') }}" class="rounded-circle mr-1">
      <div class="d-sm-none d-lg-inline-block">Hi!, {{ Auth::user()->name }}</div></a>
      <div class="dropdown-menu dropdown-menu-right">

        <a href="javascript:;" class="dropdown-item has-icon text-danger" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
          <i class="fas fa-sign-out-alt"></i> Logout
        </a>
        
        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            {{ csrf_field() }}
        </form>

      </div>
    </li>
  </ul>
</nav>

resources/views/includes/main/script.blade.php
<!-- General JS Scripts -->
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>

  <!-- Template JS File -->
  <script src="{{ asset('theme/js/scripts.js') }}"></script>
  <script src="{{ asset('theme/js/custom.js') }}"></script>

resources/views/includes/main/sidebar.blade.php
<div class="main-sidebar">
  <aside id="sidebar-wrapper">
    <div class="sidebar-brand">
      <a href="/">TREEHOTEL</a>
    </div>
    <div class="sidebar-brand sidebar-brand-sm">
      <a href="/">TH</a>
    </div>
    <ul class="sidebar-menu">
      @if (Auth::user()->role == 'USER')

        <li class="menu-header">Dashboard</li>
        <li><a class="nav-link" href="{{ route('user.dashboard') }}"><i class="fas fa-fire"></i> <span>Dashboard</span></a></li>

        <li class="menu-header">RUANGAN</li>
        <li class="{{ request()->is('room*') ? 'active' : '' }}">
          <a class="nav-link" href="{{ route('room-list.index') }}">
            <i class="fas fa-door-open"></i> <span>List Ruangan</span>
          </a>
        </li>

        <li class="menu-header">TRANSAKSI</li>
        <li class="{{ request()->is('my-booking-list*') ? 'active' : '' }}">
          <a class="nav-link" href="{{ route('my-booking-list.index') }}">
            <i class="fas fa-list"></i> <span>My Booking List</span>
          </a>
        </li>

        <li class="menu-header">SETTING</li>
        <li class="{{ request()->is('change-pass*') ? 'active' : '' }}">
          <a class="nav-link" href="{{ route('user.change-pass.index') }}">
            <i class="fas fa-key"></i> <span>Ganti Password</span>
          </a>
        </li>

      @endif

      @if (Auth::user()->role == 'ADMIN')

        <li class="menu-header">Dashboard</li>
        <li><a class="nav-link" href="{{ route('admin.dashboard') }}"><i class="fas fa-fire"></i> <span>Dashboard</span></a></li>

        <li class="menu-header">DATA MASTER</li>
        <li class="{{ request()->is('admin/room*') ? 'active' : '' }}">
          <a class="nav-link" href="{{ route('room.index') }}">
            <i class="fas fa-door-open"></i> <span>Ruangan</span>
          </a>
        </li>
        <li class="{{ request()->is('admin/user*') ? 'active' : '' }}">
          <a class="nav-link" href="{{ route('user.index') }}">
            <i class="fas fa-user"></i> <span>User</span>
          </a>
        </li>

        <li class="menu-header">TRANSAKSI</li>
        <li class="{{ request()->is('admin/booking-list*') ? 'active' : '' }}">
          <a class="nav-link" href="{{ route('booking-list.index') }}">
            @inject('booking_list', 'App\Models\BookingList')
            <i class="fas fa-list"></i> <span>{{ $booking_list->where("status", "PENDING")->count() > 0 ? '('.$booking_list->where("status", "PENDING")->count().')' : '' }} Booking List</span>
          </a>
        </li>

        <li class="menu-header">SETTING</li>
        <li class="{{ request()->is('admin/change-pass*') ? 'active' : '' }}">
          <a class="nav-link" href="{{ route('admin.change-pass.index') }}">
            <i class="fas fa-key"></i> <span>Ganti Password</span>
          </a>
        </li>

      @endif

      </ul>

  </aside>
</div>

resources/views/includes/main/style.blade.php
<!-- General CSS Files -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

<!-- Template CSS -->
<link rel="stylesheet" href="{{ asset('theme/css/style.min.css') }}">
<link rel="stylesheet" href="{{ asset('theme/css/components.min.css') }}">

{{-- admin css --}}
<link rel="stylesheet" href="{{ asset('css/admin/admin.css') }}">